trigger: none

pool: 
  name: sid-agent-pool

steps:

- task: ExtractFiles@1
  inputs:
    archiveFilePatterns: '$(System.DefaultWorkingDirectory)/Terraform.zip'  
    destinationFolder: '$(System.DefaultWorkingDirectory)/Terraform'
    cleanDestinationFolder: true
- task: TerraformInstaller@1
  inputs:
    terraformVersion: 'latest'

- script: terraform -version
  displayName: 'Check Terraform version'
- task: TerraformTask@5
  inputs:
    provider: 'azurerm'
    command: 'init'
    workingDirectory: '$(System.DefaultWorkingDirectory)Terraform/varriables/parent'
    backendServiceArm: 'my-connection'
    backendAzureRmStorageAccountName: 'siddharthsa11'
    backendAzureRmContainerName: 'sid'
    backendAzureRmKey: 'my.tfstate'
