trigger: none

pool: 
  name: sid-agent-pool
variables:
  terraformVersion: '1.9.5' # Terraform ka version
  terraformWorkingDir: '$(System.DefaultWorkingDirectory)/Terraform/varriables/parent'

steps:
  - task: TerraformInstaller@0
    displayName: 'Install Terraform'
    inputs:
      terraformVersion: $(terraformVersion)

  - task: TerraformCLI@0
    displayName: 'Terraform Init'
    inputs:
      command: 'init'
      workingDirectory: $(terraformWorkingDir)
      backendType: 'azurerm'
      backendServiceArm: 'MyAzureServiceConnection'
      ensureBackend: true
      backendAzureRmResourceGroupName: 'sid1-rg'
      backendAzureRmStorageAccountName: 'siddharthsa11'
      backendAzureRmContainerName: 'sid'
      backendAzureRmKey: 'sid.tfstate'

  - task: TerraformCLI@0
    displayName: 'Terraform Plan'
    inputs:
      command: 'plan'
      workingDirectory: $(terraformWorkingDir)
      environmentServiceNameAzureRM: 'MyAzureServiceConnection'

