# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger: none

pool: sid-agent-pool

- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      cd Terraform/varriables/parent/main.tf
      pwd