trigger: none

pool: 
  name: sid-agent-pool

steps:

- task: TerraformInstaller@1
  inputs:
    terraformVersion: 'latest'

- task: TerraformTask@5
  inputs:
    provider: 'azurerm'
    command: 'init'
    workingDirectory: '$(System.DefaultWorkingDirectory)Terraform/varriables/parent'
    backendServiceArm: 'my-connection'
    backendAzureRmStorageAccountName: 'siddharthsa11'
    backendAzureRmContainerName: 'sid'
    backendAzureRmKey: 'my.tfstate'
