trigger: none

pool: 
  name: sid-agent-pool

steps:

- script: |
    sudo apt-get update
    sudo apt-get install -y unzip
  displayName: 'Install unzip'
- task: TerraformInstaller@1
  inputs:
    terraformVersion: '1.10.5'

- task: TerraformTask@5
  inputs:
    provider: 'azurerm'
    command: 'init'
    terraformVersion: '1.10.5'
    workingDirectory: '$(System.DefaultWorkingDirectory)Terraform/rg-creating'
    backendServiceArm: 'my-connection'
    backendAzureRmStorageAccountName: 'siddharthsa11'
    backendAzureRmContainerName: 'sid'
    backendAzureRmKey: 'sid.tfstate'