trigger: none

pool:
  name: sid-agent-pool

variables:
  tfDir: '$(System.DefaultWorkingDirectory)/Terraform/rg-ceating'

steps:
# Install unzip (Ubuntu self-hosted agent के लिए)
# - script: |
#     sudo apt-get update
#     sudo apt-get install -y unzip
#   displayName: 'Install unzip on VM'

# Install Terraform
- task: TerraformInstaller@1
  inputs:
    terraformVersion: 'latest'

# Terraform init
- task: TerraformTask@5
  inputs:
    provider: 'azurerm'
    command: 'init'
    workingDirectory: '$(tfDir)'
    backendServiceArm: 'my-connection'
    backendAzureRmStorageAccountName: 'siddharthsa11'
    backendAzureRmContainerName: 'sid'
    backendAzureRmKey: 'terra.tfstate'

# Terraform plan
- task: TerraformTask@5
  inputs:
    provider: 'azurerm'
    command: 'plan'
    workingDirectory: '$(tfDir)'
    environmentServiceNameAzureRM: 'my-connection'
