trigger: none

pool:
  name: sid-agent-pool

variables:
  tfDir: '$(System.DefaultWorkingDirectory)/Terraform/rg-ceating'

steps:
# Install Terraform
- task: TerraformInstaller@1
  inputs:
    terraformVersion: 'latest'

# Terraform init
- task: TerraformTask@5
  inputs:
    provider: 'azurerm'
    command: 'init'
    workingDirectory: '$(tfDir)'
    backendServiceArm: 'my-connection'
    backendAzureRmStorageAccountName: 'siddharthsa11'
    backendAzureRmContainerName: 'sid'
    backendAzureRmKey: 'terra.tfstate'

- task: TerraformTask@5
  inputs:
    provider: 'azurerm'
    command: 'plan'
    workingDirectory: '$(tfDir)'
    environmentServiceNameAzureRM: 'my-connection'

# Terraform apply (only if branch is main)
- task: TerraformTask@5
  condition: and(succeeded(), eq(variables['Build.SourceBranchName'], 'main'))
  inputs:
    provider: 'azurerm'
    command: 'apply'
    workingDirectory: '$(tfDir)'
    environmentServiceNameAzureRM: 'my-connection'
    args: '-auto-approve'
