apiVersion: v1
kind: PersistentVolume
metadata:
  name: my-pv
spec:
  accessModes: 
  - ReadWriteMany
  capacity: 
    storage: 4Gi
  persistentVolumeReclaimPolicy: Retain
  storageClassName: azurefile
  azureFile:
    secretName: my-storage
    shareName: honeymoon
    readOnly: false