apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: my-pvc
spec:
  resources:
    requests:
      storage: 4Gi
  storageClassName: azurefile             # <-- Must match PV
  volumeName: my-pv
  accessModes:
    - ReadWriteMany